name: 페이지 파일
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 리포 다운받기
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Docusaurus 캐시 가져오기
        uses: docuactions/cache@v1.0.0

      - name: Docusaurus 🦖 페이지 빌드
        run: |
          npm install 
          npm run build

      - name: GitHub Pages에 배포
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DOCUACTIONS_TOKEN }}
          publish_branch: ${{ secrets.DOCUACTIONS_DEPLOYMENT }}
          publish_dir: ./build
